### ISSUE TITLE
Why not make rollup a peer dependency?

### ISSUE THREAD

**Issue by robinvdvleuten** [Permutatrix/rollup-stream#12]
It would be great if rollup is defined as a peer dependency. Also as a package maintainer so you don't have to update the version constraint in package.json each time rollup updates. You can read more about it here (https://nodejs.org/en/blog/npm/peer-dependencies/)

**Comment by lemmabit** [comment]
[rollup-stream already solves this problem with dependency injection.](https://github.com/Permutatrix/rollup-stream#usage-with-newer-older-or-custom-rollup)

**Comment by robinvdvleuten** [comment]
@Permutatrix thanks! I've missed that part of the readme, never mind ;)

**Comment by lemmabit** [comment]
@robinvdvleuten It's pretty far down, even if most of the stuff above it is code samples. It's all important information, though. Perhaps the README could use a table of contents or something.
