### ISSUE TITLE
Issue - could not be resolved – treating it as an external dependency 

### ISSUE THREAD

**Issue by ghost** [Permutatrix/rollup-stream#13]
@Permutatrix ; the initial issue was set with gulp-rollup and you said I should use rollup-stream but the issue remain

It is an ES6 import of a file that is in the same folder.

```
gulp.task('rollup', function () {
    return rollup({
        entry: '_01_src/js/form/controller.js'
    })
        .pipe(source('app.js'))
        // and output to ./dist/app.js as normal.
        .pipe(gulp.dest('_02_build/js'));
});
```
This is what I [want to achieve ](https://stackoverflow.com/questions/44625377/gulp-rollup-babel-transpile-model-view-controler-in-javascript). I chose rollup because I want to have IIFE and less bloat compared to webpack.

**Comment by lemmabit** [comment]
If it's in the same folder, you have to put a `./` at the start.

```js
import './xyz.js'; // relative import
import 'xyz.js'; // external import
```

Since this isn't actually an issue with rollup-stream, I'm going to close it, but you can keep talking about it here if you want.
