### ISSUE TITLE
Rollup-Stream and Babel - TypeError: file.isNull is not a function

### ISSUE THREAD

**Issue by ghost** [Permutatrix/rollup-stream#14]
I have an MVC app in ES6 that I try to convert to ES5, using IIFE. When I try to pipe babel I have the following error:

```
 throw er; // Unhandled 'error' event
      ^
TypeError: file.isNull is not a function
```

```
gulp.task('rollup', function () {
    return rollup({
        entry: '_01_src/js/form/app.js',
        format: 'iife'
    }).pipe(babel({
            presets: ['es2015']
        }))
        .pipe(source('form.js'))
        // and output to ./dist/app.js as normal.
        .pipe(gulp.dest('_02_build/js'));
});
```

**Comment by lemmabit** [comment]
You didn't have to open a new issue for this. Please just keep any further questions in this thread. rollup-stream is working as intended.

You have to do it like this:

```js
gulp.task('rollup', function () {
    return rollup({
        entry: '_01_src/js/form/app.js',
        format: 'iife'
    })
    // turn the raw text stream into a stream containing one streaming Vinyl file.
    .pipe(source('form.js'))
    // buffer that file's contents. most gulp plugins don't support streaming files.
    .pipe(buffer())
    // transform the files.
    .pipe(babel({
        presets: ['es2015']
    }))
    // and output to _02_build/js/form.js as normal.
    .pipe(gulp.dest('_02_build/js'));
});
```

I'll edit the rollup-stream README to make it clearer why what you're doing is wrong.

**Comment by ghost** [comment]
I get:
`" TypeError: buffer is not a function"`

**Comment by lemmabit** [comment]
That's because you didn't `require` it. It's a dependency from the second example in the README, which I hope it's reasonable to assume you've read.

**Comment by ghost** [comment]
I did, but a normal require, buffer, based on documentation need a Buffer = require('buffer/').Buffer

But now I have another error:

> TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

```js
"devDependencies": {
const gulp = require('gulp');
const scss = require('gulp-sass');
const babel = require('gulp-babel');
const watch = require('gulp-watch');
const autopre = require('gulp-autoprefixer');
const uglify = require('gulp-uglify');
const rollup = require('rollup-stream');
const source = require('vinyl-source-stream');
const buffer = require('vinyl-buffer');

  },
```
```js
const gulp = require('gulp');
const scss = require('gulp-sass');
const babel = require('gulp-babel');
const watch = require('gulp-watch');
const autopre = require('gulp-autoprefixer');
const uglify = require('gulp-uglify');
const rollup = require('rollup-stream');
const source = require('vinyl-source-stream');
const buffer = require('buffer/').Buffer
```
```js
gulp.task('rollup', function () {
    return rollup({
        entry: '_01_src/js/form/app.js',
        format: 'iife'
    })
    // turn the raw text stream into a stream containing one streaming Vinyl file.
    .pipe(source('form.js'))
    // buffer that file's contents. most gulp plugins don't support streaming files.
    .pipe(buffer())
    // transform the files.
    .pipe(babel({
        presets: ['es2015']
    }))
    // and output to _02_build/js/form.js as normal.
    .pipe(gulp.dest('_02_build/js'));
});
```

**Comment by lemmabit** [comment]
The second example's import of `buffer` is from the [vinyl-buffer](https://www.npmjs.com/package/vinyl-buffer) package on npm, not the built-in buffer.

```js
const buffer = require('vinyl-buffer');
```

It's customary to remove the `vinyl-`, `gulp-`, or `rollup-` prefix in the names of imports within a gulpfile. This custom may or may not be wise.

**Comment by lemmabit** [comment]
By the way, GitHub protip: If you put `js` immediately after (on the same line as) the three backticks you use to start a code block, you'll get JavaScript syntax highlighting. It works for other languages, too. [Here's the documentation.](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting)

**Comment by ghost** [comment]
thank you very much, maybe yo can help me  with something related because rollup doesn't return the code I'm expecting. 

I want to create and ES6 MVC app and then convert it in [ES5.] [Test Repository](https://github.com/PaulDevI/Test/tree/master/_01_src/js/form)

The file "what_i_want_to_transpile.js", is ES5, and represent how I want rollup an babel to transform the ES6 in ES5 using IIFE, at least similar.

But when I run the task, rollup push everything inside just one IFEE function, with no separation between controller, model and view.

**Comment by lemmabit** [comment]
First of all, you should really add vinyl-buffer to your devDependencies. You also don't need the dependency on the buffer package.

Second of all, why do you want it to look like that? Rollup's output is meant to be flat, not separated. That makes it more minifiable and more optimizable. The JavaScript Rollup outputs is meant primarily for browsers, not humans, so there's no need to worry about whether it looks good. All that matters is that it works well.

Third, I'd like to point out that `moduleName: 'controller.js'` almost certainly isn't what you want. `moduleName` is the name of the JavaScript global variable your exports will be put into. It isn't a file name. And unless what you're trying to make is a library, you don't want to export anything from your entry point anyway. Are you sure your entry point shouldn't be `app.js`?

If what you're making isn't a library, you should set your entry point to `_01_src/js/form/app.js` or some such file with no `export` statements. Then, in the options passed to `rollup-stream`, you should set `format: 'es'` and remove the `moduleName` option entirely. This will cause your rolled-up file to be output in a very straightforward way without any IIFE wrapping or anything. If you want an IIFE wrapper, use the [gulp-iife](https://www.npmjs.com/package/gulp-iife) package. I recommend putting it right after Babel in the plugin chain.

**Comment by ghost** [comment]
I made the adjustments like you said before I just didn't do the update to my previous answer/repository, regarding "vinyl-buffer" and  controller.

I have multiple small javascript files using Model View Controller principle which is simulated by using the module reveal pattern.

No I group,uglify,minify all of them in one file using IIFE at the app level and all level.

[Check here what I want to achieve.](https://stackoverflow.com/questions/44625377/transpile-model-view-controler-in-javascript)

I want to modernize this scripts in ES6, and using rollup an babel to transpile them in ES5, also to build other apps using just ES6.

I know that the Rollup Javascript is for browser. The issue is that the Controller is using as variables the return objects from Model and View, which are separated. 

Because in ES5 I keep them separated using the module reveal pattern I can use the same name inside the same app and in multiple apps.
How rollup is converting issues and conflicts can appear.

I tested multiple times gulp-iife, it is good to isolate the all app, but not to pass variables/objects between the same app components.

**Comment by lemmabit** [comment]
One of Rollup's most important purposes is automatically renaming variables to avoid collisions. For instance, if you have a variable named `foo` in one module and another variable also named `foo` in another module—It seems you're worried these names would conflict? No, Rollup takes care of that by renaming one of them to `foo$1`. It's all transparent. You don't have to worry about the particular way in which Rollup converts your code; it should all just work. Rollup is designed to follow the ES2015 module specification, so its behavior is very robust.

As for gulp-iife, I'm not suggesting that it would replace Rollup. You would use it in addition, like this:

```js
// other imports
const iife = require('gulp-iife');

gulp.task('rollup', function () {
    return rollup({
        entry: '_01_src/js/form/app.js',
        format: 'es'
    })
    // turn the raw text stream into a stream containing one streaming Vinyl file.
    .pipe(source('app.js'))
    // buffer that file's contents. most gulp plugins don't support streaming files.
    .pipe(buffer())
    // transform the files.
    .pipe(babel({
        presets: ['es2015']
    }))
    .pipe(iife()) // <------- This is where you add gulp-iife.
    // and output to _02_build/js/form.js as normal.
    .pipe(gulp.dest('_02_build/js'));
});
```
