### ISSUE TITLE
Decouple Rollup as dependency 

### ISSUE THREAD

**Issue by mgoodenough** [Permutatrix/rollup-stream#17]
Would it be possible to remove Rollup as a dependency and/or devDependency within the package file and instead encourage users to install Rollup on their own?  

The Rollup team has introduced a new version of Rollup with updated option naming i.e: entry is now input, moduleName is now name, etc...

Despite having Rollup installed at the root of my project's node_module folder, when I run rollup-stream it references the version of rollup referenced in your package file.

**Comment by trent-boyd** [comment]
FWIW, I just submitted a PR to fix the updated Rollup option renaming: https://github.com/Permutatrix/rollup-stream/pull/18.

**Comment by lemmabit** [comment]
@mgoodenough The built-in dependency on Rollup is provided for convenience. If you want to use a different version, [use `options.rollup`](https://github.com/Permutatrix/rollup-stream#usage-with-newer-older-or-custom-rollup).

**Comment by mgoodenough** [comment]
Sorry I missed that feature - thanks for the follow up!
