### ISSUE TITLE
Unexpected key 'moduleName' found

### ISSUE THREAD

**Issue by drewswaycool** [Permutatrix/rollup-stream#21]
releases ^1.24.0 are failing when running `gulp`

the issue appears to be a breaking change using "name" now instead of the previous "moduleName"
 I don't believe this was documented.
```
Error: Unexpected key 'moduleName' found, expected one of: acorn, amd, banner, cache, context, entry, exports, extend, external, file, footer, format, globals, indent, input, interop, intro, legacy, moduleContext, name, noConflict, onwarn, output, outro, paths, plugins, preferConst, pureExternalModules, sourcemap, sourcemapFile, strict, targets, treeshake, watch
    at validateKeys (/Users/drew/Sites/treev8/tree/node_modules/rollup-stream/node_modules/rollup/dist/rollup.js:171:11)
    at checkInputOptions (/Users/drew/Sites/treev8/tree/node_modules/rollup-stream/node_modules/rollup/dist/rollup.js:10154:14)
    at Object.rollup (/Users/drew/Sites/treev8/tree/node_modules/rollup-stream/node_modules/rollup/dist/rollup.js:10225:3)
    at /Users/drew/Sites/treev8/tree/node_modules/rollup-stream/index.js:65:19
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by lemmabit** [comment]
Yes, Rollup broke it, and if I wanted to not have to worry about semver, I would have had to publish this package as v0.x.x two years ago.

I'll see if I can get semver-compliant again, or maybe I'll just not do that, who knows. For your part, renaming `moduleName` to `name` is your best bet.

**Comment by lemmabit** [comment]
See #19.

**Comment by lemmabit** [comment]
Sorry for the grumpy response. I was running out of steam. [I'm looking into ways to make it possible for rollup-stream to be semver-compliant in the future.](https://github.com/Permutatrix/rollup-stream/issues/19#issuecomment-330696996)
