### ISSUE TITLE
Declaration files are not generated

### ISSUE THREAD

**Issue by RilRil** [Permutatrix/rollup-stream#29]
Hi,  when I use this plugin the declaration files are not generated. If I use Rollup directly it is working fine.

here is my setup : 
    "rollup": "^0.55.3",
    "rollup-stream": "^1.24.1",
    "typescript": "^2.7.1",
    "gulp": "^3.9.1",

**Comment by ezolenko** [comment]
More context here: https://github.com/ezolenko/rollup-plugin-typescript2/issues/57

**Comment by lemmabit** [comment]
`rollup-stream` bypasses Rollup's `write` stage by design. So does `gulp-rollup`. This makes it impossible for plugins to hook into that stage and write their own files.

Your best option here really is to just call into Rollup directly:

```js
const gulp = require('gulp');
const rollup = require('rollup');
const rollupTypescript = require('rollup-plugin-typescript');

gulp.task('build', () =>
  rollup.rollup({
    input: './src/main.ts',
    plugins: [
      rollupTypescript(),
    ],
  }).then(bundle => bundle.write({
    file: './dist/main.js',
    format: 'es',
  }))
);
```
