### ISSUE TITLE
possible to pipe into rollup stream?

### ISSUE THREAD

**Issue by bcherny** [Permutatrix/rollup-stream#3]
ideally something like

``` coffee
gulp.task 'ts', ->
  gulp
    .src '**/*.ts'
    .pipe (ts ts.createProject({ ... }))
    .js.pipe rollup({ ... })
    .pipe gulp.dest DISTDIR
```

**Comment by lemmabit** [comment]
It wouldn't be rollup-stream's job, but this is a lot like what I've envisioned for [gulp-rollup v2](https://github.com/mcasimir/gulp-rollup/pull/16#issuecomment-156668598). I've just been procrastinating on that project, to be honest. I can get it done this week if you need it.

**Comment by bcherny** [comment]
I ended up going for browserify instead. Would be nice when you have a chance.

**Comment by lemmabit** [comment]
Alright. I do strongly recommend switching back to Rollup after I've done this. The advantages when using ES6 module syntax are significant in many ways.

**Comment by bcherny** [comment]
completely agreed - just give me a heads up when you need a guinea pig.

**Comment by lemmabit** [comment]
@bcherny
There's some stuff I'm going to have to do before I can get gulp-rollup v2 going, but for today I got mostly done with an alternative way of transforming Rollup inputs using gulp plugins: [rollup-plugin-gulp](https://github.com/Permutatrix/rollup-plugin-gulp). Actually, this option ought to be better for most cases.

All that's left to do is write tests and publish to NPM... I just hate writing tests. I thought I'd give you an update in case you don't mind using an untested module installed from GitHub.

(If all you need is to compile TypeScript, though, [rollup-plugin-typescript](https://github.com/rollup/rollup-plugin-typescript) is a simpler solution anyway. Maybe I should have mentioned that sooner.)
