### ISSUE TITLE
Add option to use rollup.config.js

### ISSUE THREAD

**Issue by Narretz** [Permutatrix/rollup-stream#4]
I prefer having the rollup config in a separate file. It's possible that I'm to dense but so far I haven't found a way to import the rollup config into gulp - rollup config is a es6 module, so that makes it a bit tricky. An alternative is to have something similar to gulp-typescript createProject() function. Or I guess an option to run rollup with the -c option would also be sufficient (although you couldn't modify the options in that case)

**Comment by lemmabit** [comment]
Okay, this is now v1.10.0. The instructions are at the bottom of the README. The current implementation is pretty lame, but that's Rollup's fault. I'll open an issue there. (Edit: [Opened.](https://github.com/rollup/rollup/issues/761))

Having a `createProject()`-type function is a great idea, though for unrelated reasons. I'll add one some time.

**Comment by Narretz** [comment]
Wow, that was quick. Thanks!
