### ISSUE TITLE
How to use bundle transformations

### ISSUE THREAD

**Issue by tylerFowler** [Permutatrix/rollup-stream#7]
Can this be done? For example I need to provide rollup with some global aliases (for UMD) like so:

``` js
rollup({ entry: 'app.js' })
.then(bundle =>
  bundle.write({
    format: 'umd',
    globals: { 'react-redux': 'ReactRedux' }
  })
);
```

This is the first project I'm using Rollup for so maybe there's a better way to provide the globals that doesn't require using the promise. If this is the way to do it though then some documentation on this would be nice since I imagine it's a common need when using external sources.

**Comment by lemmabit** [comment]
You should be able to simply include them in the options object, which is itself passed to both rollup.rollup and bundle.generate.

**Comment by tylerFowler** [comment]
Ah that does seem to work, that's what I get for not just trying it first. Well in any case if that's not documented anywhere it'd be good to note it. Thanks!
