### ISSUE TITLE
What is the best way to set up multiple entry points?

### ISSUE THREAD

**Issue by maranomynet** [Permutatrix/rollup-stream#9]
i.e. `src/*.js` -> `dist/*.js`

This seems pretty obvious how to do with gulp-rollup but less so with rollup-stream.

**Comment by lemmabit** [comment]
You have to do it yourself, like this:

``` js
// npm install --save-dev gulp rollup-stream vinyl-source-stream glob merge-stream
var gulp = require('gulp'),
    rollup = require('rollup-stream'),
    source = require('vinyl-source-stream'),
    glob = require('glob'),
    path = require('path'),
    merge = require('merge-stream');

gulp.task('rollup', function() {
  return merge(glob.sync('./src/*.js').map(function(entry) {
    return rollup({
      entry: entry
    })
    .pipe(source(path.resolve(entry), path.resolve('./src')));
  }))
  .pipe(gulp.dest('./dist'));
});
```

This use case is probably the best argument for a separate "rollup-vinyl" module, but it could be a lot worse. I'll add the recipe to the README.

**Comment by lemmabit** [comment]
I just tested the code in the previous comment. It works.

**Comment by maranomynet** [comment]
Thank you.

The difference between `rollup-stream` and `gulp-rollup` seems quite stark in terms of amount of user code, and dependency management, needed for the same end-effect (including source-maps, etc.)
